name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.2
  firebase_core: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

 
