// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqI2DFDd9yOHK_rLxxZwliT_PuWwW7FB4',
    appId: '1:781085968731:web:f38d71a979f251c1f0b27e',
    messagingSenderId: '781085968731',
    projectId: 'jjlksukuna',
    authDomain: 'jjlksukuna.firebaseapp.com',
    storageBucket: 'jjlksukuna.firebasestorage.app',
    measurementId: 'G-G42YKMTHW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1UGZMxv776oUsxFC5uLIPfn5qsLgGHLI',
    appId: '1:781085968731:android:85604a5ae7b4e6faf0b27e',
    messagingSenderId: '781085968731',
    projectId: 'jjlksukuna',
    storageBucket: 'jjlksukuna.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATvKSW0Skrs7_FHaH_nSS1FhA-2pCoxxE',
    appId: '1:781085968731:ios:21dae261506f2c73f0b27e',
    messagingSenderId: '781085968731',
    projectId: 'jjlksukuna',
    storageBucket: 'jjlksukuna.firebasestorage.app',
    iosBundleId: 'com.flutterthailand.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATvKSW0Skrs7_FHaH_nSS1FhA-2pCoxxE',
    appId: '1:781085968731:ios:21dae261506f2c73f0b27e',
    messagingSenderId: '781085968731',
    projectId: 'jjlksukuna',
    storageBucket: 'jjlksukuna.firebasestorage.app',
    iosBundleId: 'com.flutterthailand.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqI2DFDd9yOHK_rLxxZwliT_PuWwW7FB4',
    appId: '1:781085968731:web:8caf923d707f3235f0b27e',
    messagingSenderId: '781085968731',
    projectId: 'jjlksukuna',
    authDomain: 'jjlksukuna.firebaseapp.com',
    storageBucket: 'jjlksukuna.firebasestorage.app',
    measurementId: 'G-CSLRS84Q8G',
  );

}