// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmYur87YxxSB-zabo7JZpBS5_NJD23CtQ',
    appId: '1:863694413966:web:a7113d810c809aa785a9df',
    messagingSenderId: '863694413966',
    projectId: 'fir-mo-187cf',
    authDomain: 'fir-mo-187cf.firebaseapp.com',
    storageBucket: 'fir-mo-187cf.firebasestorage.app',
    measurementId: 'G-X2270VDC4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBragtCS_Y-JoDNniOLWq63KgNO1pM9SoQ',
    appId: '1:863694413966:android:32ddceb94d1820ad85a9df',
    messagingSenderId: '863694413966',
    projectId: 'fir-mo-187cf',
    storageBucket: 'fir-mo-187cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0yP1Q50o89KJUwRAy-gHRAMnUUJN0DVY',
    appId: '1:863694413966:ios:64d7eb4d9d1905be85a9df',
    messagingSenderId: '863694413966',
    projectId: 'fir-mo-187cf',
    storageBucket: 'fir-mo-187cf.firebasestorage.app',
    iosBundleId: 'com.flutterthailand.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0yP1Q50o89KJUwRAy-gHRAMnUUJN0DVY',
    appId: '1:863694413966:ios:64d7eb4d9d1905be85a9df',
    messagingSenderId: '863694413966',
    projectId: 'fir-mo-187cf',
    storageBucket: 'fir-mo-187cf.firebasestorage.app',
    iosBundleId: 'com.flutterthailand.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmYur87YxxSB-zabo7JZpBS5_NJD23CtQ',
    appId: '1:863694413966:web:9460ab155a1beabd85a9df',
    messagingSenderId: '863694413966',
    projectId: 'fir-mo-187cf',
    authDomain: 'fir-mo-187cf.firebaseapp.com',
    storageBucket: 'fir-mo-187cf.firebasestorage.app',
    measurementId: 'G-0VQE4B44Q1',
  );

}